s390: add missing show_registers() declaration
The generic show_registers() declaration is only available for
CONFIG_KPROBES, which is a bit odd.
In order to fix a build problem with our zfcpdump_defconfig add an
s390 speficic declaration.

Fixes this build error:
arch/s390/kernel/process.c: In function 'set_fs_fixup':
arch/s390/kernel/process.c:251:2: error: implicit declaration of function 'show_registers'

Please merge with "s390: restore address space when returning to user space"
(166-restore-asce-on-user-return.diff)

Signed-off-by: Heiko Carstens <heiko.carstens@de.ibm.com>