s390/nmi: fix non-smp compile
NMI now calls smp_emergency()_stop instead of smp_send_stop().
This causes the following error for CONFIG_SMP=n:

arch/s390/kernel/nmi.c: In function 's390_handle_damage':
arch/s390/kernel/nmi.c:126:2: error: implicit declaration of function 'smp_emergency_stop'; did you mean 'emergency_sync'? [-Werror=implicit-function-declaration]
  smp_emergency_stop();
  ^~~~~~~~~~~~~~~~~~
  emergency_sync

For smp_send_stop() the common header include/linux/smp.h
defines an empty inline for CONFIG_SMP=n. For smp_emergency_stop
the s390 header needs to do this.

To be merged with git commit c6b8cf6add593888be0c9c7bebca751d9019c9a8
"s390/nmi: use smp_emergency_stop instead of smp_send_stop"

Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>