driver core: Fix dev_printk() with CONFIG_KMSG_IDS
Steffen reported use of dev_printk() in zfcp internal inject causes
Kernel build to fail. Problem can be reproduced without any internal
injects in Kernel build with DEBUG as follows:

$ make EXTRA_CFLAGS='-DDEBUG'
...
  MODPOST vmlinux.o
drivers/s390/cio/css.o: In function `css_evaluate_known_subchannel':
.../drivers/s390/cio/css.c:501: undefined reference to `_dev_printk_hash'
Makefile:1036: recipe for target 'vmlinux' failed
make: *** [vmlinux] Error 1

Fix naming of macro and function declaration to match function definition
in arch/s390/kernel/kmsg.c. While at it add __printf() and __cold
annotations to function declaration.

Reported-by: Steffen Maier <maier@linux.ibm.com>
Suggested-by: Heiko Carstens <heiko.carstens@de.ibm.com>
Signed-off-by: Jens Remus <jremus@linux.ibm.com>
Fixes: 028798f2b502 ("Update to v4.19-rc2")