libperf: fix build error with LIBPFM4=1
Fix build error with LIBPFM4=1:
  CC      util/pfm.o
util/pfm.c: In function ‘parse_libpfm_events_option’:
util/pfm.c:102:30: error: ‘struct evsel’ has no member named ‘leader’
  102 |                         evsel->leader = grp_leader;
      |                              ^~

Fixes: fba7c86601e2 ("libperf: Move 'leader' from tools/perf to perf_evsel::leader")
Signed-off-by: Heiko Carstens <hca@linux.ibm.com>