s390: fix include order fallout
Heikos patch to move the thread_info to task_struct and the
preempt-count rework will cause compile errors if
CONFIG_HAVE_MARCH_Z196_FEATURES=n

./arch/s390/include/asm/preempt.h: In function '__preempt_count_dec_and_test':
./include/linux/thread_info.h:17:54: error: 'current' undeclared (first use in this function)
 #define current_thread_info() ((struct thread_info *)current)

Fix this by including asm/current.h before linux/thread_info.h
in asm/preempt.

To be merged with git commit e2bcf56ee762ae4cc1a241832eab299fda0a9701
"s390/preempt: move preempt_count to the lowcore"

Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>