crypto des: add missing select statement
Add missing "select CRYPTO_DES". Fixes this:
ERROR: "des_ekey" [arch/s390/crypto/des_s390.ko] undefined!

Signed-off-by: Heiko Carstens <heiko.carstens@de.ibm.com>