s390/dasd: add missing EXPORT_SYMBOL
Fixes this:
ERROR: "dasd_set_feature" [drivers/s390/block/dasd_fba_mod.ko] undefined!

Please merge with 511-dasd-discard-support.diff
("s390/dasd: Add discard support for FBA devices")

Signed-off-by: Heiko Carstens <heiko.carstens@de.ibm.com>