s390: fix build for CRASH_DUMP=n
Fix this compile error for CONFIG_CRASH_DUMP=n builds:
arch/s390/built-in.o: In function `setup_arch':
/root/src/linux/arch/s390/kernel/setup.c:875: undefined reference to `smp_save_dump_cpus'
make: *** [vmlinux] Error 1

Introduced via e7a4310 (s390/kdump: fix nosmt kernel parameter).

Please merge with e7a4310 s390/kdump: fix nosmt kernel parameter.

Signed-off-by: Sebastian Ott <sebott@linux.vnet.ibm.com>