fixup! s390/cio: remove unused include linux/spinlock.h from cio.h
Due to headers changes upstream merging v5.14-rc1 into devel produces
the following build error:

arch/s390/kernel/ipl_vmparm.c: In function ‘ipl_block_get_ascii_vmparm’:
arch/s390/kernel/ipl_vmparm.c:18:23: error: implicit declaration of function ‘min_t’ [-Werror=implicit-function-declaration]
   18 |                 len = min_t(size_t, size - 1, ipb->ccw.vm_parm_len);
      |                       ^~~~~

While v5.14-rc1 itself builds just fine.

Adding a fixup for commit e9309faa70b5 ("s390/cio: remove unused include
linux/spinlock.h from cio.h") which fixes this build problem.

Signed-off-by: Vasily Gorbik <gor@linux.ibm.com>