s390/ipl: conditional compile of IPL report helper
An allnoconfig compile fails with this message:

arch/s390/kernel/ipl.c: In function 'ipl_report_add_component':
arch/s390/kernel/ipl.c:1736:25: error: dereferencing pointer to incomplete type 'struct kexec_buf'
  comp->entry.addr = kbuf->mem;

Add #ifdef CONFIG_KEXEC_FILE around the ipl report helper to fix this.

To be merged with git commit 62fa8b45d8ca14888e2e46fd1607f11387fc163e
"s390/ipl: add helper functions to create an IPL report"

Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>