fixup! fixup! s390: correct CALL_ON_STACK back_chain saving
replace always inline function with a macro to avoid the following build
error on gcc < 8 when kasan is enabled.

In file included from arch/s390/kernel/smp.c:56:0:
arch/s390/kernel/smp.c: In function ‘pcpu_delegate’:
./arch/s390/include/asm/stacktrace.h:72:38: error: inlining failed in call
to always_inline ‘current_frame_address’: function attribute mismatch
 static __always_inline unsigned long current_frame_address(void)
                                      ^~~~~~~~~~~~~~~~~~~~~
./arch/s390/include/asm/stacktrace.h:111:16: note: called from here
  unsigned long frame = current_frame_address();   \
                ^
arch/s390/kernel/smp.c:325:3: note: in expansion of macro ‘CALL_ON_STACK’
   CALL_ON_STACK(__pcpu_delegate, stack, 2, func, data);
   ^~~~~~~~~~~~~
To be merged with commit afcb7d2f7e5b ("s390: correct CALL_ON_STACK
back_chain saving").

Signed-off-by: Vasily Gorbik <gor@linux.ibm.com>